In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a = [10, 20, 30, 40]

for i, v in enumerate(a):   
    print(f"i = {i}, v = {v}")
    a[i] = v * 2
a

i = 0, v = 10
i = 1, v = 20
i = 2, v = 30
i = 3, v = 40


[20, 40, 60, 80]

In [8]:
b = np.array(a)
b *= 2
print(b)

[ 40  80 120 160]


In [19]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
from random import randint

marks = [randint(40, 100) for i in range(100)]
print(marks)

[73, 61, 81, 92, 95, 91, 42, 92, 73, 95, 49, 51, 85, 54, 84, 66, 67, 61, 60, 54, 89, 74, 80, 88, 75, 56, 78, 77, 70, 46, 77, 89, 72, 87, 68, 98, 55, 82, 80, 73, 67, 47, 74, 48, 67, 100, 73, 62, 57, 45, 55, 72, 71, 47, 87, 66, 60, 95, 65, 83, 65, 57, 48, 65, 95, 59, 47, 78, 55, 66, 87, 81, 85, 42, 66, 53, 75, 80, 90, 61, 87, 96, 96, 49, 61, 51, 68, 40, 87, 70, 84, 86, 96, 47, 72, 95, 88, 48, 85, 59]


In [25]:
random = np.random.randint(40, 100, 10)
print(random)

[69 51 90 71 75 98 77 93 94 81]


In [27]:
print(np.random.randn(10))
print(np.random.random_sample(10))
print(np.random.randint(10, 20, [3, 3]))

[-0.00296129 -0.85121484  0.27049021 -0.36650634 -0.01322658  0.63761825
  1.7348783   0.27879339 -0.36596306  1.46194627]
[0.85935049 0.88524078 0.6149427  0.43389753 0.52709385 0.00593807
 0.69097054 0.46302093 0.30387168 0.22382817]
[[18 14 10]
 [15 18 17]
 [11 14 10]]


In [31]:
m = np.arange(1, 10).reshape(3, 3)
print(np.matmul(m,m))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [33]:
import numpy as np

a = np.arange(1, 28).reshape((3, 3, 3))
print(a)

print(f'size =     {a.size}')      
print(f'itemsize = {a.itemsize}')
print(f'nbytes =   {a.nbytes}')
print(f'ndim =     {a.ndim}')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
size =     27
itemsize = 8
nbytes =   216
ndim =     3


In [ ]:
import numpy as np
z = np.array([1, 2, 3, 4, 5])

In [ ]:
print(np.mean(z))
print(np.median(z))
print(np.min(z))
print(np.max(z))
print(np.nonzero(z))
print(np.mod(z, 2))
print(np.std(z))
print(np.var(z))
print(np.eye(3))
print(np.ones((3,4)))
print(np.zeros((3,4)))

3.0
3.0
1
5
(array([0, 1, 2, 3, 4]),)
[1 0 1 0 1]
1.4142135623730951
2.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
w = np.arange(1,21)

In [ ]:
w.reshape(5, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
w.reshape(2, 5, -1).argmax(1)

array([[4, 4],
       [4, 4]])

In [ ]:
w.argmax(0)

np.int64(19)

In [ ]:
np.linspace(0,1,199)

array([0.        , 0.00505051, 0.01010101, 0.01515152, 0.02020202,
       0.02525253, 0.03030303, 0.03535354, 0.04040404, 0.04545455,
       0.05050505, 0.05555556, 0.06060606, 0.06565657, 0.07070707,
       0.07575758, 0.08080808, 0.08585859, 0.09090909, 0.0959596 ,
       0.1010101 , 0.10606061, 0.11111111, 0.11616162, 0.12121212,
       0.12626263, 0.13131313, 0.13636364, 0.14141414, 0.14646465,
       0.15151515, 0.15656566, 0.16161616, 0.16666667, 0.17171717,
       0.17676768, 0.18181818, 0.18686869, 0.19191919, 0.1969697 ,
       0.2020202 , 0.20707071, 0.21212121, 0.21717172, 0.22222222,
       0.22727273, 0.23232323, 0.23737374, 0.24242424, 0.24747475,
       0.25252525, 0.25757576, 0.26262626, 0.26767677, 0.27272727,
       0.27777778, 0.28282828, 0.28787879, 0.29292929, 0.2979798 ,
       0.3030303 , 0.30808081, 0.31313131, 0.31818182, 0.32323232,
       0.32828283, 0.33333333, 0.33838384, 0.34343434, 0.34848485,
       0.35353535, 0.35858586, 0.36363636, 0.36868687, 0.37373