# NUMPY BASICS

In [2]:
import numpy as np  # Import the numpy library as np

# Create a NumPy array with integers from 1 to 10
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# [id(a[i]) for i in range(10)]
# [id(i) for i in a]

# print addresses of each element.
# does not work as expected in python.
# because of how python lets us interact with addresses.

In [ ]:
import numpy as np  # Import the numpy library as np

# Create a NumPy array with integers from 1 to 10
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("multiply:", a * 2)     # Multiply each element by 2 (element-wise)
print("divide:", a / 2)       # Divide each element by 2 (element-wise)
print("add:", a + 2)          # Add 2 to each element (element-wise)
print("subtract:", a - 2)     # Subtract 2 from each element (element-wise)
print("exponent:", a ** 2)    # Raise each element to the power of 2 (element-wise)

multiply: [ 2  4  6  8 10 12 14 16 18 20]
divide: [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
add: [ 3  4  5  6  7  8  9 10 11 12]
subtract: [-1  0  1  2  3  4  5  6  7  8]
exponent: [  1   4   9  16  25  36  49  64  81 100]


In [ ]:
import numpy as np  # Import the numpy library

# Create a NumPy array with integers from 1 to 10
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(type(a))        # Print the type of 'a' (should be <class 'numpy.ndarray'>)
print(a.dtype)        # Print the data type of the array elements (e.g., int64 or int32)

a = a.astype(np.int16)  # Convert array 'a' to have elements of type int16

print(a.dtype)        # Print the new data type (should be int16)

<class 'numpy.ndarray'>
int64
int16


In [ ]:
import numpy as np

# Create a NumPy array containing integers and a string "hello"
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, "hello"])

print(a)
# Prints the entire array, note all elements are now strings because of mixed types
print(a.dtype)
# Data type will be '<U21' (unicode string) because of presence of a string in the list

# Slice the array to exclude the last element ("hello"), then convert elements to int16
a = a[:-1].astype(np.int16)

print(a, a.dtype)
# Prints the integer array without "hello" and confirms dtype is now int16

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' 'hello']
<U21
[ 1  2  3  4  5  6  7  8  9 10] int16


In [22]:
# dimensions of an arrange.
import numpy as np
my_1D_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

my_2D_arr = np.array([
         [1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]
])

my_3D_arr = np.array([
         [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
         [[1, 2, 3], [1, 2, 3], [1, 2, 3]],
         [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
])

# print(f"shape: {my_1D_arr.shape}, dimensionsmy_1D_arr.ndim)
# print(my_2D_arr.shape, my_2D_arr.ndim)
# print(my_3D_arr.shape, my_3D_arr.ndim)

(9,) 1
(3, 3) 2
(3, 3, 3) 3


In [ ]:
import numpy as np  # Import NumPy library for numerical operations

# Create a NumPy array with values from 1 to 36 and reshape into a 6x6 matrix
a = np.arange(1, 37).reshape(6, 6)

# Print the 6x6 matrix
print(a)

# Print the element in 4th row, 4th column (indexing starts at 0)
print(a[3][3])

# Print elements in 5th row, columns 4 to 5 (upper bound excluded)
print(a[4][3:5])

# Print elements in 6th row, columns 4 to 6 (upper bound excluded)
print(a[5][3:6])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [ ]:
import numpy as np  # Import NumPy library for numerical operations

# Create a NumPy array with values from 1 to 36 and reshape into a 6x6 matrix
a = np.arange(1, 37).reshape(6, 6)

# Loop through rows with index 3 to 5 (4th to 6th row)
for i in range(3, 6):
    # Print elements from column index 3 up to (but not including) column index (i + 1)
    print(a[i][3: i + 1])

[22]
[28 29]
[34 35 36]


In [1]:
import numpy as np  # Import NumPy for numerical operations

# Create a 3x3 matrix filled with zeros (integer type: 16-bit signed)
print(np.zeros((3, 3), dtype=np.int16))

# Create a 3x3 matrix filled with ones (integer type: 16-bit signed)
print(np.ones((3, 3), dtype=np.int16))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 3x3 NumPy array with a diagonal-like pattern of 1's
a = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])

# Find the indices of all non-zero elements in the array
print(np.nonzero(a))

(array([0, 1, 2]), array([2, 1, 0]))


In [2]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 3x3 NumPy array with some zero and non-zero integer values
a = np.array([[12, 0, 1335],
              [0, 16, 0],
              [133, 0, 83]])

# Select and print all non-zero elements from the array
print(a[np.nonzero(a)])

[  12 1335   16  133   83]


In [3]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 3x3 NumPy array with some zero and non-zero integer values
a = np.array([[12, 0, 1335],
              [0, 16, 0],
              [133, 0, 83]])

# Use advanced (fancy) indexing to select specific elements by (row, column) positions
print(a[([0, 0, 1, 2, 2], [0, 0, 1, 2, 2])])

[12 12 16 83 83]


In [ ]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 3x3 NumPy array with both zero and non-zero integer values
a = np.array([[12, 0, 1335],
              [0, 16, 0],
              [133, 0, 83]])

# Print all elements of 'a' that are greater than zero
print(a[a > 0])

[  12 1335   16  133   83]


In [ ]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 1D NumPy array of integers from 1 to 9
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Print elements greater than 5
print(a[(a > 5)])   # Output: [6 7 8 9]

# Print elements less than 8
print(a[(a < 8)])   # Output: [1 2 3 4 5 6 7]

# Print elements greater than 5 AND less than 8
print(a[(a > 5) & (a < 8)])  # Output: [6 7]

[6 7 8 9]
[1 2 3 4 5 6 7]
[6 7]


In [6]:
import numpy as np
a = np.array([1, 2, 3, 6, 7, 8])
count = (a > 5).sum()  # counts how many elements are greater than 5
print(count)  # Output: 3

3


In [7]:
import numpy as np  # Import NumPy library

# Create an array of years from 1947 to 2025 inclusive
years = np.arange(1947, 2026)

# Select leap years using the standard leap year rules:
# - Divisible by 4 and not by 100, OR divisible by 400
leap_years = years[((years % 4 == 0) & (years % 100 != 0)) | (years % 400 == 0)]

print(leap_years)  # Output all leap years in the given range

[1948 1952 1956 1960 1964 1968 1972 1976 1980 1984 1988 1992 1996 2000
 2004 2008 2012 2016 2020 2024]


In [8]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 1D array of integers from 1 to 27, then reshape into a 3x3x3 array (3D matrix)
a = np.arange(1, 28).reshape((3, 3, 3))
print(a)  # Display the 3D array

# Total number of elements in the array
print(a.size)       # Output: 27

# Size (in bytes) of each element
print(a.itemsize)   # Usually 8 bytes for default 'int64' on most systems

# Total bytes consumed by the array in memory
print(a.nbytes)     # Equals size × itemsize (27 × 8 = 216 bytes here)

# Number of dimensions (axes) of the array
print(a.ndim)       # Output: 3 (since it's a 3D array)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
27
8
216
3


In [ ]:
import numpy as np  # Import NumPy library for numerical operations

# Create 26 evenly spaced values from 0 to 1 (inclusive)
a = np.linspace(0, 1, 26)
print(a)  # Print the evenly spaced values

# Generate 25 random floats between 0.0 and 1.0
random = np.random.random(25)
print(random)  # Print the random values

[0.   0.04 0.08 0.12 0.16 0.2  0.24 0.28 0.32 0.36 0.4  0.44 0.48 0.52
 0.56 0.6  0.64 0.68 0.72 0.76 0.8  0.84 0.88 0.92 0.96 1.  ]
[0.09870979 0.11542437 0.74570342 0.49785036 0.41492009 0.08967446
 0.84532708 0.06108666 0.70137679 0.71245606 0.82712169 0.53742544
 0.44052354 0.11017428 0.25392864 0.58780845 0.38792007 0.66494267
 0.9152376  0.84426552 0.62106446 0.033418   0.97781081 0.4353406
 0.39955184]


In [ ]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 1D array of 25 random integers from 1 to 24 (inclusive of 1, exclusive of 25)
# Then reshape it into a 5x5 matrix
array = np.random.randint(1, 25, 25).reshape(5, 5)

# Print the generated 5x5 random integer matrix
print(array)

[[ 7 11  2 10  5]
 [24 15 16 16 22]
 [23 11  7 14 10]
 [14 22 14 14 10]
 [ 5 24 18 20 24]]


In [ ]:
import numpy as np  # Import NumPy library

# Assume 'array' is your 2D NumPy array (e.g., a 5x5 matrix)

# Loop over each row index in 'array'
for i in range(array.shape[0]):
    # Print the maximum value in the i-th row (all columns of row i)
    print(array[i, :].max())

# Loop over each column index in 'array'
for i in range(array.shape[1]):
    # Print the maximum value in the i-th column (all rows of column i)
    print(array[:, i].max())

11
24
23
22
24


In [ ]:
# similarily, print sum of each column

import numpy as np  # Import NumPy library for numerical operations

array = np.random.randint(1, 25, 25).reshape(5, 5)

for i in range(array.shape[0]):
    print(array[:, i].sum())

42
49
66
56
72


In [ ]:
# similarily, print minimum of each column

import numpy as np  # Import NumPy library for numerical operations

array = np.random.randint(1, 25, 25).reshape(5, 5)

for i in range(array.shape[0]):
    print(array[:, i].min())

2
1
3
6
4


In [ ]:
# similarily, print mean of each column

import numpy as np  # Import NumPy library for numerical operations

array = np.random.randint(1, 25, 25).reshape(5, 5)

for i in range(array.shape[0]):
    print(array[:, i].mean())

9.2
3.8
7.8
12.6
12.4


In [ ]:
import numpy as np  # Import NumPy library

# Assume 'array' is an existing 2D NumPy array (e.g., 5x5 integers)

# Print all elements in the first row, followed by its maximum value
print(array[0, :], array[0, :].max())

# Print all elements in the second column, followed by its maximum value
print(array[:, 1], array[:, 1].max())

[ 7 11  2 10  5] 11
[11 15 11 22 24] 24


In [15]:
import numpy as np  # Import NumPy library

# Assume 'array' is your existing 2D NumPy array (e.g., shape 5x5)
array = np.random.randint(1, 25, 25).reshape(5, 5)

# Select all rows, but only columns 0, 1, and 2 (slice up to column index 3)
print(array[:, 0:3])

# Select rows with indices 2 and 4, and all their columns
print(array[(2, 4), :])

[[10 14  8]
 [20 10 17]
 [12 24  2]
 [10  6 24]
 [16 10 13]]
[[12 24  2 24 18]
 [16 10 13 13 11]]


In [ ]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 1D array of 25 random integers from 1 to 24 (inclusive of 1, exclusive of 25)
# Then reshape it into a 5x5 matrix
array = np.random.randint(1, 25, 25).reshape(5, 5)

# Convert the 2D array into a 1D array (flattened)
print(array.flatten())

[ 7 11  2 10  5 24 15 16 16 22 23 11  7 14 10 14 22 14 14 10  5 24 18 20
 24]


In [22]:
import numpy as np  # Import NumPy library for numerical operations

# Create a 1D array of 25 random integers from 1 to 24,
# then reshape it into a 5x5 matrix
array = np.random.randint(1, 25, 25).reshape(5, 5)

# Create a 1D iterator over the array elements (row‑major order by default)
n = array.flat

In [23]:
print(n[0])  # first element
print(n[7])  # 8th element

23
5


In [24]:
for value in n:
    print(value)  # prints each element in order

23
14
18
2
14
21
17
5
11
17
9
7
12
9
2
7
2
5
5
22
19
10
22
4
24
